# Generated by Django 4.2.20 on 2025-04-17 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('content', models.TextField()),
                ('materials', models.TextField()),
                ('time_taken', models.IntegerField(help_text='Time taken in minutes')),
                ('age', models.IntegerField(choices=[(0, '5+'), (1, '8+'), (2, '10+'), (3, '13+'), (4, '15+'), (5, '18+')], default=0)),
                ('media_url', models.URLField(blank=True, null=True)),
                ('skill', models.IntegerField(choices=[(0, 1), (1, 2), (2, 3), (3, 4), (4, 5)], default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='craft_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
