# Generated by Django 4.2.20 on 2025-04-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='craft-images/default card.jpg', upload_to='craft-images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='media_url',
            field=models.URLField(blank=True, help_text='Link to your Youtube/Facebook, etc', null=True),
        ),
    ]
