# Generated by Django 4.2.20 on 2025-04-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafts', '0002_post_image_alter_post_media_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='media/craft-images/default card.jpg', upload_to='media/craft-images/'),
        ),
    ]
