# Generated by Django 4.2.20 on 2025-04-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafts', '0003_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='category-images/default card.jpg', upload_to='category-images/'),
        ),
    ]
